"""Create tables

Revision ID: 20bb0acc3ca2
Revises:
Create Date: 2025-11-28 12:30:01.361126

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "20bb0acc3ca2"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bucket",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("bucket_name", sa.String(length=128), nullable=False),
        sa.Column(
            "bucket_last_clean",
            sa.DateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("bucket_name"),
    )
    op.create_table(
        "directory",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dir_path", sa.String(length=512), nullable=False),
        sa.Column("dir_bucket_id", sa.Integer(), nullable=False),
        sa.Column(
            "dir_last_clean",
            sa.DateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["dir_bucket_id"],
            ["bucket.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dir_path"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("directory")
    op.drop_table("bucket")
    # ### end Alembic commands ###
